language: go

go:
  - 1.13.x

go_import_path: github.com/amarjeetanandsingh/tgconst

script:
  - go build
notifications:
  email:
    #    recipients:
    #      - one@example.com
    #      - other@example.com
    on_success: never
    on_failure: always
