language: go

go:
  - 1.11.x
  - 1.13.x
  - master

go_import_path: github.com/amarjeetanandsingh/tgcon

env:
  global:
    - GO111MODULE=on

script:
  - go test -race -coverprofile=cover.out -coverpkg=./... ./...
  - go tool cover -html=cover.out -o cover.html

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
