language: go

go:
  - 1.11.x
  - 1.13.x
  - master

go_import_path: github.com/amarjeetanandsingh/tgconst

env:
  global:
    - GO111MODULE=on

script:
  - go test ./...
  - go build

notifications:
  email:
    on_success: never
    on_failure: always
